[package]
name = "chess_gm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shakmaty = "0.24"

tokio = { version = "1", features = ["full"] }